/// Flutter icons Car
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Car
///      fonts:
///       - asset: fonts/Car.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CarIcon {
  CarIcon._();

  static const _kFontFam = 'Car';

  static const IconData money = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cab = const IconData(0xf1b9, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xf4ac, fontFamily: _kFontFam);
}
